-- 코드를 입력
SELECT P.PRODUCT_CODE, SUM(P.PRICE * O.SALES_AMOUNT) AS 매출액
FROM PRODUCT AS P
INNER JOIN OFFLINE_SALE AS O
ON P.PRODUCT_ID = O.PRODUCT_ID
GROUP BY P.PRODUCT_CODE
ORDER BY 매출액 DESC, PRODUCT_CODE
;
